remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: false

title: Luis Fernando Machado Poletti Valle
logo: "/images/profile.jpg?raw=true"
description: >
  Software Engineer and Data Scientist with 5 years of industry and research experience.
  <br><br>
  Between 2018 and 2021 I worked as a full-stack software engineer at Bloomberg L.P. I also acted as a Python trainer for new software engineers, and contributed to the inner source Python Guild.
  <br><br>
  2021-2023: Physics MSc at ETH Zurich. GPA: 5.85/6.0
  2014-2018: Astrophysics BSc at Yale University. GPA: 3.94/4.0
  <br><br>
  <a href="https://www.linkedin.com/in/luisfernandomachado/">My LinkedIn Profile</a>